language: cpp

dist: trusty
sudo: required

git:
  depth: 10

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: linux
      dist: trusty

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ./util/osx/prepare.sh & ./util/osx/prepare.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./util/ubuntu/prepare.sh & sudo ./util/ubuntu/prepare.sh; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ./util/osx/build.sh & ./util/osx/build.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./util/ubuntu/build.sh & ./util/ubuntu/build.sh; fi

deploy:
  - provider: releases
    api_key:
      secure: "YcYuUSA61KuQ2YjLsJHZziUOwyWNrxiiqjd16U1ZL7j517Ff/i0JgKuSXj/nkeRUIwXz16YRVxUnLLy6w8aGuMJiVldRtJ8+qY5zesaPNk8gdrU6I6Hv7g5O0lgqKd1rZIFd5wzfcKJ6GEKphsWmNL/TJgMaBB9n32tSR4hizen37ZD+cmjoipm6YNMCA7Fku8r8qafsJE3H1pTjyNBsGe4O08V56BZZwewL95M+f/6KwdIY094f/WfhqfqcF0pLIGRoiWIOizpAlNArqAVMCXUOzg01yPjRlx+yDLFe4ow5rHDb9tzaKWqrFpOJZkx0s/4mP13hKZ6nn7wxnB+Q6hm82biJhGNOQqy3lGKqUUu0kQBhNjmPsooJhsBz9sJynG5mTf7CnPHXCY3CjF779VYPhzXMXyt0quNpbr+NpY9SykQCeFnEPsMsijg5EN/q/hkvk2g5P05Ryr2wJvmITSC5NLZ/Xxla8T1ICsiwurMbq8BnVi9gLABwvH5lxlqWm/Ucvo5yrn9WF4oYMlylQmfHKzDkhSXX5aiIHZDmw/aFeA0FxE/p1YQQHJZ/Y18Q7ExVQLcG6L2Hjs+7Xx/wQMpEtYZ/Y6ymX2TutdM4Pfguoh7Tz6esxETsh1h2jHdZzuQ3E8QRIIOoobYIfMaW+iVAY1VBWh5iI+nAIkXlvcs="
    file_glob: true
    file: "QtcDbViewer-*.tar.gz"
    skip_cleanup: true
    on:
      tags: true

notifications:
  email:
    on_success: change
    on_failure: change
