name: Plugin build

on: [push]

jobs:
  release:
    name: Create release
    if: contains(github.ref, '/tags/')
    runs-on: ubuntu-16.04
    steps:
      - name: Create release
        if: contains(github.ref, '/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Store release url
        run: echo "${{ steps.create_release.outputs.upload_url }}" > ./release_upload_url

      - name: Upload release url
        uses: actions/upload-artifact@v1
        with:
          path: ./release_upload_url
          name: release_upload_url

  build:
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env:
      OS: ${{ matrix.config.name }}
      msvc_version: 2019/Enterprise
    strategy:
      matrix:
        config:
          - { name: "win64", os: windows-latest }
          - { name: "win32", os: windows-latest }
          - { name: "linux", os: ubuntu-16.04 }
          - { name: "macos", os: macos-latest }
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - name: Install system libs
        if: runner.os == 'Linux'
        run: sudo apt install libgl1-mesa-dev

      - name: Get Qt
        run: python ./util/ci/get_qt.py

      - name: Get Qt Creator
        run: python ./util/ci/get_qtc.py

      - name: Build plugin
        run: python ./util/ci/build.py

      - name: Download release url
        if: contains(github.ref, '/tags/')
        uses: actions/download-artifact@v1
        with:
          name: release_upload_url
          path: ./

      - name: Set env
        shell: bash
        run: |
          echo ::set-env name=upload_url::`cat ./release_upload_url || true`
          echo ::set-env name=artifact::`python ./util/ci/build.py artifact_name`

      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.artifact }}
          path: ./${{ env.artifact }}

      - name: Upload release artifacts
        if: contains(github.ref, '/tags/')
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.upload_url }}
          asset_path: ./${{ env.artifact }}
          asset_name: ${{ env.artifact }}
          asset_content_type: application/zip
